### ISSUE TITLE
Existential type question ("extremely important trick")

### ISSUE THREAD

**Issue by brianberns** [nickcowle/Talks#1]
Please help me understand how this:

```
(∃T List<T>) -> U
```

Is equivalent to this:

```
(∀T List<T> -> U)
```

Thanks!

**Comment by nickcowle** [comment]
Of course! I think the easiest way to explain this is in words, so let's do that first:

What's the type of the first function? It takes an existentially quantified `List<T>` and returns something of type `U`. But what is the type of `T` inside our existentially quantified `List<T>`? Well, it could be anything! So, in effect, the first function is able to take a `List<T>` for any type `T` (inside the existential quantifier) and return `U`. But if it can do that – take any `List<T>` for any `T` and return `U`, then it must surely be equivalent to a function that takes `List<T>` for any `T` and returns `U`. That’s exactly the signature of the second function.

Don’t take my word for it, though – if these two types really are equivalent then we should be able to convert between the two of them. So, let’s do just that. Here are the type definitions that we will need:

```fsharp
// Here, ListCrate is our encoding of ∃T List<T>
type ListEvaluator<'ret> = abstract member Eval<'a> : 'a list -> 'ret
type ListCrate = abstract member Apply<'ret> : ListEvaluator<'ret> -> 'ret

// The type of the first function
// (∃T List<T>) -> U
type Func1<'u> = ListCrate -> 'u

// The type of the second function
// ∀T (List<T> -> U)
type Func2<'u> = abstract member Invoke<'a> : 'a list -> 'u
```

We also need a utility method to be able to turn a `List<T>` to a `ListCrate` (i.e. to existentially quantify `T`):

```fsharp
// Utility method to 'crate up' a list, i.e. existentially quantify it
let crateList (xs : 'a list) : ListCrate =
    { new ListCrate with
        member __.Apply eval = eval.Eval xs
    }
```

Now let's write some conversion functions convert between the two representations:

```fsharp
let func1ToFunc2 (f1 : Func1<'u>) : Func2<'u> =
    { new Func2<'u> with
        member __.Invoke<'a> (xs : 'a list) : 'u =
            f1 (crateList xs)
    }

let func2ToFunc1 (f2 : Func2<'u>) : Func1<'u> =
    fun crate ->
        crate.Apply
            { new ListEvaluator<'u> with
                member __.Eval<'a> (xs : 'a list) : 'u =
                    f2.Invoke xs
            }
```

Since we can convert back and forth between these two representations, they are in some sense equivalent. 

Finally, let’s talk about the logical interpretation of what’s going on here. In [First-order logic]( https://en.wikipedia.org/wiki/First-order_logic), we have the two quantifiers `∀` (for all) and `∃` (there exists). There exist some important identities relating `∀`, `∃` and `¬` (negation). In particular (you can find this on the [Wikipedia page]( https://en.wikipedia.org/wiki/First-order_logic#Provable_identities)) the following identity is important for us:
```
¬∀x P(x) ⟺ ∃x ¬P(x)
```

This identity tells us that the follow two statements are equivalent:
1. It is not the case that for all `x`, `P(x)` is true
2. There exists some `x` such that `P(x)` is not true

Hopefully, it’s intuitively obvious why these two statements are equivalent from their descriptions. But look at what happens symbolically here – to get from the first statement to the second, we effectively pulled out the universal quantifier over the negation. In the process of pulling the quantifier out over the negation, it flips from a universal quantifier to an existential quantifier.

This is exactly what is happening what is happening with the two function types in the "extremely important trick". In the first type, the existential quantifier is stuck inside the left-hand side of an implication (the `->`). Because implication works in a similar way to negation for the inputs, we can pull the existential quantifier out over the implication, and in doing so it flips to a universal quantifier.

Doing so takes us from:
```
(∃T List<T>) -> U
```
to:
```
∀T (List<T> -> U)
```
which gives us the result that we want.

Hope that helps,
Nick

**Comment by brianberns** [comment]
This is great. Thank you for the detailed explanation. The connection to first-order logic really helps.

Since I opened the issue, I've been slowly researching and educating myself about universal/existential types. I decided to translate what you've done into C# step-by-step, just to make sure I understand it, and have been blogging about it [here](https://dev.to/shimmer).

I think what you all are doing at G-Research sounds very interesting. It's great to see some type theory being put to use in the F# world. Usually it's the Haskellers who have all the fun! :)
